<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3b042baa-74dd-4f54-8a86-a1f658977c23</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[2]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>:root &gt; :nth-child(2) &gt; :nth-child(2) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(2) &gt; :nth-child(2)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-1ommr5q')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-1ommr5q</value>
        <webElementGuid>5e473804-1aee-4599-984a-c6b5c055a774</webElementGuid>
    </webElementProperties>
</WebElementEntity>