<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ce2918e0-9252-4d12-8e28-f84fc5822c7a</elementGuidId>
    <imagePath></imagePath>
    <name>input_combo_box_demo</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#combo-box-demo</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'combo-box-demo') and equals(@class,'MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedEnd MuiAutocomplete-input MuiAutocomplete-inputFocused css-1563wdh')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedEnd MuiAutocomplete-input MuiAutocomplete-inputFocused css-1563wdh</value>
        <webElementGuid>fad13d89-8f81-4061-a751-cb83c5ba9e2f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>combo-box-demo</value>
        <webElementGuid>b89e81b9-1016-435a-a27f-1c7e76463061</webElementGuid>
    </webElementProperties>
</WebElementEntity>